/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/views/**/*.htm','./app/views/**/*.html',
    './app/views/**/*.php',
    './app/views/**/*.js',
    './install/view/**/*.php',
    './install/view/**/*.htm',
    './plugins/**/view/**/*.{htm,php,html}',
    './plugins/**/views/**/*.{htm,php,html}',
    './plugins/**/*.js',
    './themes/**/*.htm',
    './themes/**/*.php',
  ],
  safelist: [
    'absolute','accent-blue-600','animate-bounce','animate-pulse','animate-spin','appearance-none','aspect-square','backdrop-blur-sm',
    'bg-blue-50','bg-blue-600','bg-gradient-to-l','bg-gray-100','bg-gray-200','bg-gray-300','bg-gray-50','bg-gray-50/50','bg-gray-50/95','bg-gray-900/50','bg-green-100','bg-red-100','bg-slate-100','bg-white','bg-yellow-100',
    'block','border','border-2','border-[40px]','border-b','border-black/50','border-blue-100','border-collapse','border-gray-100','border-gray-200','border-gray-300','border-gray-50','border-t','border-transparent','border-white','border-white/20','border-white/80',
    'bottom-0','bottom-12','bottom-2','bottom-4','break-words',
    'cursor-move','cursor-pointer',
    'dark:bg-blue-900/20','dark:bg-gray-600','dark:bg-gray-700','dark:bg-green-900/30','dark:bg-red-900/30','dark:bg-slate-600','dark:bg-slate-700','dark:bg-slate-800','dark:bg-slate-800/50','dark:bg-slate-900','dark:bg-slate-900/90','dark:bg-white/5','dark:bg-yellow-900/30',
    'dark:border-blue-900/30','dark:border-gray-600','dark:border-gray-700','dark:border-gray-700/50','dark:border-gray-800','dark:border-slate-700',
    'dark:from-slate-800','dark:hover:bg-red-900/20','dark:hover:bg-slate-600','dark:hover:bg-slate-700','dark:hover:bg-white/10','dark:hover:bg-white/5','dark:hover:text-blue-200','dark:text-blue-400','dark:text-gray-200','dark:text-gray-300','dark:text-gray-400','dark:text-gray-500','dark:text-green-400','dark:text-red-400','dark:text-white','dark:text-yellow-400',
    'duration-200','duration-300',
    'fixed','flex','flex-1','flex-col','flex-nowrap','flex-shrink-0','focus:outline-none','focus:ring-2','focus:ring-blue-500','focus:ring-offset-2','font-bold','font-medium','font-mono','font-normal','font-semibold','font-serif','from-white',
    'gap-1','gap-2','gap-3','glass-panel','grid','grid-cols-2','group','group-hover:opacity-100','group-hover:text-blue-500',
    'h-1.5','h-10','h-12','h-2','h-3','h-32','h-4','h-48','h-5','h-6','h-8','h-auto','h-full','hidden',
    'hover:bg-blue-700','hover:bg-gray-100','hover:bg-gray-200','hover:bg-gray-50','hover:bg-red-50','hover:text-blue-700','hover:text-blue-900','hover:text-gray-500','hover:underline',
    'inline-block','inline-flex','inset-0','inset-y-0','italic','items-center','items-start','justify-between','justify-center','justify-end',
    'last:border-0','leading-6','left-0','left-1/2','left-2','left-4','line-through','lowercase',
    'max-h-64','max-h-[70vh]','max-w-[320px]','max-w-[calc(100vw-2rem)]','max-w-full','max-w-none','mb-1','mb-3','mb-4','mb-6','min-h-full','ml-1','ml-2','ml-3','mr-1','mr-2','mr-3','mt-2','mt-3','mx-1','mx-auto','my-2','my-4','my-auto',
    'opacity-0','opacity-25','opacity-75','origin-center','outline-none','overflow-hidden','overflow-x-auto','overflow-y-auto',
    'p-1','p-1.5','p-12','p-2','p-3','p-4','p-8','pb-10','pb-4','pointer-events-auto','pointer-events-none','pr-2','pt-1','pt-2','pt-5','px-2','px-3','px-4','py-0.5','py-1.5','py-2','py-3',
    'relative','right-0','right-2','right-4','rounded','rounded-2xl','rounded-full','rounded-lg','rounded-t-xl','rounded-xl','scroll-smooth',
    'shadow-2xl','shadow-[0_0_0_9999px_rgba(0,0,0,0.5)]','shadow-lg','shadow-sm','shadow-xl',
    'sm:flex','sm:flex-row-reverse','sm:items-start','sm:max-w-sm','sm:ml-3','sm:ml-4','sm:mt-0','sm:p-6','sm:pb-4','sm:px-6','sm:text-left','sm:text-sm','sm:w-auto',
    'space-x-2','space-x-4','space-y-3','space-y-4',
    'text-[10px]','text-base','text-blue-500','text-blue-600','text-center','text-gray-400','text-gray-500','text-gray-600','text-gray-700','text-gray-900','text-green-500','text-green-600','text-left','text-lg','text-purple-600','text-red-500','text-red-600','text-sm','text-white','text-white/50','text-xs','text-yellow-500','text-yellow-600','to-transparent','top-0','top-14','top-4','tracking-wider','transform','transition-all','transition-colors','transition-opacity','translate-x-full','truncate','underline','uppercase',
    'w-1','w-10','w-12','w-16','w-2','w-24','w-3','w-4','w-5','w-6','w-64','w-8','w-80','w-[calc(100vw-2rem)]','w-full','w-px','whitespace-nowrap',
    'z-20','z-30','z-50','z-[60]','z-[61]',
  ],
  theme: {
    extend: {
      colors: {
        slate: {
          850: '#1e293b',
          900: '#0f172a',
        },
        brand: {
          50: '#f0f7ff',
          100: '#e0effe',
          200: '#bae0fd',
          300: '#7cc8fb',
          400: '#38acf7',
          500: '#0f8aed',
          600: '#026dce',
          700: '#0357a6',
          800: '#084a87',
          900: '#0d3f70',
        },
      },
      animation: {
        'gradient': 'gradient 8s linear infinite',
        'float': 'float 6s ease-in-out infinite',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'blob': 'blob 7s infinite',
        'spin-slow': 'spin 10s linear infinite',
      },
      keyframes: {
        gradient: {
          '0%, 100%': { 'background-size': '200% 200%', 'background-position': 'left center' },
          '50%': { 'background-size': '200% 200%', 'background-position': 'right center' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        blob: {
          '0%': { transform: 'translate(0px, 0px) scale(1)' },
          '33%': { transform: 'translate(30px, -50px) scale(1.1)' },
          '66%': { transform: 'translate(-20px, 20px) scale(0.9)' },
          '100%': { transform: 'translate(0px, 0px) scale(1)' },
        },
      },
    },
  },
  plugins: [],
}
